version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 9595:8080
  rabbitmq:
    image: 'rabbitmq:3.13.6-management'
    ports:
      - '15672:15672'
      - '5672:5672'
  stock-api:
    build:
      dockerfile: ./src/Stock/Stock.Api/Dockerfile
    ports: 
      - '8001:8080'
  stock-consumer:
    build:
      dockerfile: ./src/Stock/Stock.Consumer/Dockerfile
  order-api:
    build:
      dockerfile: ./src/Order/Order.Api/Dockerfile
    ports: 
      - '8002:8080'  
  order-consumer:
    build:
      dockerfile: ./src/Order/Order.Consumer/Dockerfile
  notification-consumer:
    build:
      dockerfile: ./src/Notification/Notification.Consumer/Dockerfile                          